name: GitHub Classroom Workflow

on: workflow_dispatch

env:
  DEVOPS_DIR: devops
  GHSECRET: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  copy-issues:
    # copy all issues from the template to the students repo
    env:
      SCRIPT_REPO: BZZ-Commons/copy-issues
      SOURCE_REPO: BZZ-Commons/copy-issues  # TODO set the owner/name of the source repo
      TARGET_REPO: ${{ github.repository }}
      ADD_LABELS: "true"  # should the labels for the issues be added
    if: ${{ contains(github.actor, 'classroom') }}
    name: CopyIssues
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyGithub
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Check-out the IssueCopy Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.SCRIPT_REPO }}
          path: ${{ env.DEVOPS_DIR }}
      - name: Copy the Issues
        run: python ${{ env.DEVOPS_DIR }}/issues.py
        shell: sh