name: GitHub Classroom autograding and update moodle

on: 
  workflow_call:
    inputs:
      MOODLE:
        default: false
        required: false
        type: boolean
env:
  DEVOPS_DIR: devops
  GHSECRET: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  grading:
    # autograding an assignment in GitHub Classroom
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # checkout the content of the repository
      - uses: ghwalin/autograder@master
        # run the test cases in .github/classroom/autograding.json
        id: autograding
      - name: grade-moodle-assignment
        # grade the assignment in Moodle, runs even after an error in autograding
        if: ${{ inputs.MOODLE }}
        run: |
          #!/bin/bash
          grade=${{ steps.autograding.outputs.Points }}
          parts=(${grade//\// })
          points=${parts[0]}
          feedback="${{ steps.autograding.outputs.Feedback }}"
          user=${{ github.actor }}
          
          repofull=${{ github.repository }}
          parts=(${repofull//\// })
          reponame=${parts[1]}
          template="${reponame/"-${{ github.actor }}"/""}"
          assignment=$template
          token=${{secrets.MOODLE_TOKEN}}
          echo ${{secrets.MOODLE_TOKEN}} | sed 's/./& /g'
                    
          curl -X POST "${{ vars.MOODLE_URL}}?wstoken=$token&wsfunction=local_gradeassignments_update_grade
             -H "Content-Type: application/x-www-form-urlencoded"
             --data-urlencode "assignment_name=$template"
             --data-urlencode "user_name=$user"
             --data-urlencode "points=$points"
             --data-urlencode "feedback=$feedback"
