name: GitHub Classroom setup

on: 
  workflow_call:
    inputs:
      SOURCE_REPO:
        required: true
        type: string
      TARGET_REPO:
        required: true
        type: string
      ADD_LABELS:
        required: true
        type: string

env:
  DEVOPS_DIR: devops
  SCRIPT_REPO: BZZ-Commons/copy-issues
  GHSECRET: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: read
  contents: read

jobs:
    copy-issues:
      name: CopyIssues
      runs-on: ubuntu-latest
      steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyGithub
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Check-out the IssueCopy Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.SCRIPT_REPO }}
          path: ${{ env.DEVOPS_DIR }}
      - name: Copy the Issues
        run: python ${{ inputs.DEVOPS_DIR }}/issues.py
        shell: sh
