name: GitHub Classroom setup

on: 
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string

env:
  DEVOPS_DIR: devops

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  copy-issues:
    name: copy issues
    runs-on: ubuntu-latest
    steps:
      - name: copy
        run: |
          echo ${{ inputs.source_repo }}
